//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class recaudacionVehiculos {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cabecera", typeof(recaudacionVehiculosCabecera), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("detallesPagos", typeof(recaudacionVehiculosDetallesPagos), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class recaudacionVehiculosCabecera {
    
    private string codigoBancoField;
    
    private string nombreBancoField;
    
    private string fechaRecaudacionField;
    
    private string numeroTransaccionesDirectasMATRICULAField;
    
    private string numeroTransaccionesReversadasMATRICULAField;
    
    private string numeroTransaccionesTotalesMATRICULAField;
    
    private string montoTransaccionesDirectasMATRICULAField;
    
    private string montoTransaccionesReversasMATRICULAField;
    
    private string montoTotalTransaccionesMATRICULAField;
    
    private string numeroTransaccionesDirectasTRANSF_DOMField;
    
    private string numeroTransaccionesReversadasTRANSF_DOMField;
    
    private string numeroTransaccionesTotalesTRANSF_DOMField;
    
    private string montoTransaccionesDirectasTRANSF_DOMField;
    
    private string montoTransaccionesReversasTRANSF_DOMField;
    
    private string montoTotalTransaccionesTRANSF_DOMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoBanco {
        get {
            return this.codigoBancoField;
        }
        set {
            this.codigoBancoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nombreBanco {
        get {
            return this.nombreBancoField;
        }
        set {
            this.nombreBancoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fechaRecaudacion {
        get {
            return this.fechaRecaudacionField;
        }
        set {
            this.fechaRecaudacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesDirectasMATRICULA {
        get {
            return this.numeroTransaccionesDirectasMATRICULAField;
        }
        set {
            this.numeroTransaccionesDirectasMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesReversadasMATRICULA {
        get {
            return this.numeroTransaccionesReversadasMATRICULAField;
        }
        set {
            this.numeroTransaccionesReversadasMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesTotalesMATRICULA {
        get {
            return this.numeroTransaccionesTotalesMATRICULAField;
        }
        set {
            this.numeroTransaccionesTotalesMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTransaccionesDirectasMATRICULA {
        get {
            return this.montoTransaccionesDirectasMATRICULAField;
        }
        set {
            this.montoTransaccionesDirectasMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTransaccionesReversasMATRICULA {
        get {
            return this.montoTransaccionesReversasMATRICULAField;
        }
        set {
            this.montoTransaccionesReversasMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTotalTransaccionesMATRICULA {
        get {
            return this.montoTotalTransaccionesMATRICULAField;
        }
        set {
            this.montoTotalTransaccionesMATRICULAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesDirectasTRANSF_DOM {
        get {
            return this.numeroTransaccionesDirectasTRANSF_DOMField;
        }
        set {
            this.numeroTransaccionesDirectasTRANSF_DOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesReversadasTRANSF_DOM {
        get {
            return this.numeroTransaccionesReversadasTRANSF_DOMField;
        }
        set {
            this.numeroTransaccionesReversadasTRANSF_DOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numeroTransaccionesTotalesTRANSF_DOM {
        get {
            return this.numeroTransaccionesTotalesTRANSF_DOMField;
        }
        set {
            this.numeroTransaccionesTotalesTRANSF_DOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTransaccionesDirectasTRANSF_DOM {
        get {
            return this.montoTransaccionesDirectasTRANSF_DOMField;
        }
        set {
            this.montoTransaccionesDirectasTRANSF_DOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTransaccionesReversasTRANSF_DOM {
        get {
            return this.montoTransaccionesReversasTRANSF_DOMField;
        }
        set {
            this.montoTransaccionesReversasTRANSF_DOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string montoTotalTransaccionesTRANSF_DOM {
        get {
            return this.montoTotalTransaccionesTRANSF_DOMField;
        }
        set {
            this.montoTotalTransaccionesTRANSF_DOMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class recaudacionVehiculosDetallesPagos {
    
    private recaudacionVehiculosDetallesPagosDetallePago[] detallePagoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detallePago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public recaudacionVehiculosDetallesPagosDetallePago[] detallePago {
        get {
            return this.detallePagoField;
        }
        set {
            this.detallePagoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class recaudacionVehiculosDetallesPagosDetallePago {
    
    private recaudacionVehiculosDetallesPagosDetallePagoPago[] pagoField;
    
    private string tipoPagoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public recaudacionVehiculosDetallesPagosDetallePagoPago[] pago {
        get {
            return this.pagoField;
        }
        set {
            this.pagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoPago {
        get {
            return this.tipoPagoField;
        }
        set {
            this.tipoPagoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class recaudacionVehiculosDetallesPagosDetallePagoPago {
    
    private string codTranIFIRevField;
    
    private string tipoTxField;
    
    private string codLogMonField;
    
    private string codTranIFIField;
    
    private string codValRecField;
    
    private string placaCpnCamvField;
    
    private string valorDebitarField;
    
    private string fechaPagoField;
    
    private string estadoDebitoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codTranIFIRev {
        get {
            return this.codTranIFIRevField;
        }
        set {
            this.codTranIFIRevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tipoTx {
        get {
            return this.tipoTxField;
        }
        set {
            this.tipoTxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codLogMon {
        get {
            return this.codLogMonField;
        }
        set {
            this.codLogMonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codTranIFI {
        get {
            return this.codTranIFIField;
        }
        set {
            this.codTranIFIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codValRec {
        get {
            return this.codValRecField;
        }
        set {
            this.codValRecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string placaCpnCamv {
        get {
            return this.placaCpnCamvField;
        }
        set {
            this.placaCpnCamvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valorDebitar {
        get {
            return this.valorDebitarField;
        }
        set {
            this.valorDebitarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fechaPago {
        get {
            return this.fechaPagoField;
        }
        set {
            this.fechaPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string estadoDebito {
        get {
            return this.estadoDebitoField;
        }
        set {
            this.estadoDebitoField = value;
        }
    }
}
